# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 07:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=b'C:\\Users\\Admin\\Desktop\\mini\\media\\images')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Title')),
                ('uuid', models.CharField(max_length=36, verbose_name=b'Unique Identifier')),
                ('document_url', models.URLField(verbose_name=b'Document_Url')),
                ('date_uploaded', models.DateTimeField()),
                ('key1', models.CharField(max_length=300, verbose_name=b'key1')),
                ('key2', models.CharField(max_length=300, verbose_name=b'key2')),
                ('key3', models.CharField(max_length=300, verbose_name=b'key3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
